# Generated by Django 4.1 on 2024-01-20 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonents', '0002_abonent_login_mikrotik'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTinkoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stamp', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinkoff_payments', to='abonents.abonent')),
            ],
            options={
                'verbose_name': 'Платеж Тинькофф',
                'verbose_name_plural': 'Платежи Тинькофф',
            },
        ),
    ]
