# Generated by Django 4.1 on 2024-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_payments', '0003_alter_paymenttinkoff_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttinkoff',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
