# Generated by Django 4.1 on 2024-01-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_payments', '0004_alter_paymenttinkoff_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttinkoff',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
