# Generated by Django 4.1 on 2023-12-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('bandwidth', models.IntegerField()),
                ('month_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
