# Generated by Django 4.1 on 2023-12-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_bandwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='bandwidth',
            field=models.CharField(max_length=100),
        ),
    ]
