# Generated by Django 4.1 on 2023-12-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_bandwidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_guid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
