# Generated by Django 4.1 on 2023-12-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_group_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='month_price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
