# Generated by Django 4.1 on 2023-12-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_month_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
    ]
