# Generated by Django 4.1 on 2023-12-25 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0006_alter_group_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('account_number', models.CharField(max_length=30, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ip_addr', models.GenericIPAddressField(null=True, unique=True)),
                ('block', models.BooleanField(default=False)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('credit', models.CharField(blank=True, max_length=200, null=True)),
                ('credit_check', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('passport', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.group')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, null=True)),
                ('new_balance', models.CharField(max_length=200, null=True)),
                ('abonent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='abonents.abonent')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
