# Generated by Django 4.1 on 2023-12-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonent',
            name='login_mikrotik',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
