# Generated by Django 4.1 on 2024-01-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0002_abonent_login_mikrotik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
