# Generated by Django 4.1 on 2024-01-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonents', '0003_alter_abonent_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSberbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(blank=True, max_length=30, null=True)),
                ('txn_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sberbank_payments', to='abonents.abonent')),
            ],
            options={
                'verbose_name': 'Платеж Сбербанк',
                'verbose_name_plural': 'Платежи Сбербанк',
            },
        ),
    ]
