# Generated by Django 4.1 on 2024-01-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sberbank_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsberbank',
            name='txn_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
