# Generated by Django 4.1 on 2024-01-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sberbank_payments', '0002_alter_paymentsberbank_txn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsberbank',
            name='txn_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
